package org.acme.static_.openapi.document.generator.extension.runtime;

import org.eclipse.microprofile.openapi.OASFilter;
import org.eclipse.microprofile.openapi.models.OpenAPI;

public final class MyFilter implements OASFilter {

    @Override
    public void filterOpenAPI(OpenAPI openAPI) {
        openAPI.getInfo().description("This description was generated by the extension - in the filter");
    }
}
