package org.acme.static_.openapi.document.generator.extension.deployment;

import io.quarkus.deployment.annotations.BuildProducer;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.builditem.FeatureBuildItem;
import io.quarkus.deployment.builditem.GeneratedResourceBuildItem;
import io.quarkus.smallrye.openapi.deployment.spi.AddToOpenAPIDefinitionBuildItem;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

class StaticOpenapiDocumentGeneratorExtensionProcessor {

    private static final String OPENAPI_CONTENT = "openapi: 3.0.1\n" +
                                                  "info:\n" +
                                                  "  description: This description was generated by the extension";

    private static final String FEATURE = "static-openapi-document-generator-extension";

    @BuildStep
    FeatureBuildItem feature() {
        return new FeatureBuildItem(FEATURE);
    }



    @BuildStep
    void generatedResource(BuildProducer<AddToOpenAPIDefinitionBuildItem> addToOpenAPIDefinitionProducer, BuildProducer<GeneratedResourceBuildItem> generatedResourceProducer) throws IOException {
        String sourcesDestinationDirectory = "META-INF/openapi.yaml";
        byte[] contentBytes = OPENAPI_CONTENT.getBytes();

        Files.write(Path.of("target/classes/META-INF/openapi.yaml"),
                contentBytes);

        generatedResourceProducer.produce(new GeneratedResourceBuildItem(
                sourcesDestinationDirectory, contentBytes, false));
    }
}
